PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 1

LINEAGE_BUILD_DATE := $(shell date +%y%m%d-%H%M)

YAOYORO_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILD)

# Internal version
YAOYORO_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(YAOYORO_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(YAOYORO_VERSION_SUFFIX)

ifeq ($(YAOYORO_MAINTAINER),)
    TARGET_YAOYORO_MAINTAINER := buildbot
else
    TARGET_YAOYORO_MAINTAINER := $(YAOYORO_MAINTAINER)
endif
